[package]
name = "ratatui-elm"
version = "0.1.0-alpha.4"
edition = "2024"
authors = ["Devin Droddy <devin@justdeeevin.dev>"]
license = "MIT"
repository = "https://github.com/justdeeevin/ratatui-elm"
description = "A simple Elm architecture framework for ratatui"
readme = "README.md"
keywords = ["tui", "elm", "framework", "ratatui"]
categories = ["command-line-interface", "asynchronous"]

[dependencies]
ratatui = "0.29.0"
futures = { version = "0.3.31", default-features = false, features = ["alloc"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "sync", "macros"] }
